#!/bin/sh
set -eu

APP_DB_USER="${APP_DB_USER:-claimflow_app}"
APP_DB_PASSWORD="${APP_DB_PASSWORD:-${POSTGRES_PASSWORD:-}}"
POSTGRES_DB_NAME="${POSTGRES_DB:-noodledoc}"
POSTGRES_ADMIN_USER="${POSTGRES_USER:-postgres}"

if [ -z "${APP_DB_PASSWORD}" ]; then
  echo "APP_DB_PASSWORD or POSTGRES_PASSWORD must be set" >&2
  exit 1
fi

# Create/refresh a dedicated non-superuser application role so runtime traffic
# cannot bypass RLS through the default Postgres superuser account.
psql -v ON_ERROR_STOP=1 -U "${POSTGRES_ADMIN_USER}" -d "${POSTGRES_DB_NAME}" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_DB_USER}') THEN
    EXECUTE format(
      'CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT',
      '${APP_DB_USER}',
      '${APP_DB_PASSWORD}'
    );
  ELSE
    EXECUTE format(
      'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT',
      '${APP_DB_USER}',
      '${APP_DB_PASSWORD}'
    );
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "${POSTGRES_DB_NAME}" TO "${APP_DB_USER}";
GRANT USAGE ON SCHEMA public TO "${APP_DB_USER}";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${APP_DB_USER}";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "${APP_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${APP_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${APP_DB_USER}";
SQL
